"""empty message

Revision ID: 51dc5b5d4aa1
Revises: 
Create Date: 2026-01-30 13:19:52.582401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51dc5b5d4aa1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f('books_name_key'), type_='unique')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_unique_constraint(batch_op.f('books_name_key'), ['name'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
